#! /usr/bin/env python3

import sys
from point import Point
import matplotlib.pyplot as plt

def create_list_point(path):
	try:
		list = [0] * (len(open(path, "r").readlines()))
	except:
		print("Bad file")
		sys.exit(84)
	i = 0
	for s in open(path, "r").readlines():
		try:
			s = s.split(';')
			assert(len(s) == 2)
			float(s[0])
			float(s[1])
		except:
			print("Bad point")
			sys.exit(84)
		list[i] = Point(s[0], s[1])
		i = i + 1
	list = sorted(list, key=lambda Point: Point.x)
	return (list)

def calcul(list, i):
	try:
		res = (list[i + 1].y - list[i - 1].y) / (list[i + 1].x - list[i - 1].x)
	except:
		print("division by zero")
		sys.exit(84)
	return (res)

def derivative(list):
	i = 1
	new_list = [0] * (len(list) - 2)
	while i != len(list) - 1:
		try:
			assert(list[i].x == int(list[i].x))
			print("volume:	%i ml" % int(list[i].x), "-> %.2f" % calcul(list, i))
		except:
			print("volume:	%.1f ml" % list[i].x, "-> %.2f" % calcul(list, i))
		new_list[i - 1] = Point(list[i].x, calcul(list, i))
		i = i + 1
	return (new_list)

def find_equivalent_point(list):
	mem = list[0]
	for s in list:
		if abs(s.y) > mem.y:
			mem = s
	try:
		assert(int(mem.x) == mem.x)
		print("\nEquivalent point at %i ml" % mem.x)
	except:
		print("\nEquivalent point at %.1f ml" % mem.x)

def display_graph(list, color, size):
	list_x = [s.x for s in list]
	list_y = [s.y for s in list]
	plt.plot(list_x, list_y, color, linewidth=size)

def titration():
	list = create_list_point(sys.argv[1])
	display_graph(list, "r", 5)
	print("Derivative:")
	list = derivative(list)
	display_graph(list, "g", 1)
	find_equivalent_point(list)
	print("\nSecond derivative:")
	list = derivative(list)
	display_graph(list, "b", 1)
	plt.xlabel("VOLUME")
	plt.ylabel("CONCENTRATION")
	plt.show()

if __name__ == "__main__":
	if len(sys.argv) != 2:
		print("Miss file")
		sys.exit(84)
	titration()
	sys.exit(0)
